[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vocabulary-learning"
version = "0.1.0"
description = "A tool for learning vocabulary"
requires-python = ">=3.8"
dependencies = [
    "numpy==1.24.3",
    "pandas==2.0.3",
    "rich==13.5.2",
    "googletrans==3.1.0a0",
    "pykakasi==2.2.1",
]

[project.scripts]
vocabulary-learning = "vocab_learner.__main__:main"

[tool.hatch.build.targets.wheel]
packages = ["vocab_learner"]

[tool.uv]
install = [
    "uv",
    "numpy==1.24.3",
    "pandas==2.0.3",
    "rich==13.5.2",
    "googletrans==3.1.0a0",
    "pykakasi==2.2.1",
]
