name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      FIREBASE_CREDENTIALS_PATH: ${{ github.workspace }}/tests/fixtures/mock-firebase-credentials.json
      FIREBASE_DATABASE_URL: https://test-db.firebaseio.com
      FIREBASE_USER_EMAIL: test@example.com
      PYTHONIOENCODING: utf-8
      LANG: ja_JP.UTF-8
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Set up Japanese locale
      run: |
        sudo apt-get update
        sudo apt-get install -y language-pack-ja
        sudo update-locale LANG=ja_JP.UTF-8
        
    - name: Create mock Firebase credentials
      run: |
        mkdir -p tests/fixtures
        echo '{"type": "service_account"}' > tests/fixtures/mock-firebase-credentials.json
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install the package with dev dependencies
        pip install -e ".[dev]"
        pip install flake8-docstrings
        
    - name: Check code formatting with Black
      run: |
        black --check --line-length=100 vocabulary_learning tests
        
    - name: Check imports with isort
      run: |
        isort --check-only --profile black --line-length 100 vocabulary_learning tests
        
    - name: Lint with flake8
      run: |
        flake8 vocabulary_learning tests \
          --max-line-length=100 \
          --extend-ignore=E203,W503,E722,E501 \
          --per-file-ignores="__init__.py:D104 tests/*:D101,D100 vocabulary_learning/utils/*:D100,D103,F841" \
          --ignore=D107,D101,F541,D400,D103
        
    - name: Run tests with coverage
      run: |
        mkdir -p test-results
        pytest tests/ --cov=vocabulary_learning --cov-report=xml --cov-report=html:test-results/coverage
      env:
        PYTHONPATH: ${{ github.workspace }}
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: true
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results/
          coverage.xml
        retention-days: 30 